_schema: _schema
paths:
  uploads: image/uploads
  static: ''
collections_config:
  pages:
    path: pages
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
      - visual
      - source
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  page_content:
    path: content/pages
    name: Page Content
    icon: description
    disable_url: true
    description: Structured JSON backing inline page editing.
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_properties:
    path: content/properties
    name: Content Properties
    icon: content_paste
    disable_url: true
    description: JSON snippets for property page sections.
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    description: Structured datasets for listings and blog posts.
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Riga
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
