_schema: _schema
paths:
  uploads: image/uploads
  static: ''
  data: content/pages
  collections: content
preserve_files:
  - image/uploads

collections_config:
  site_pages:
    path: pages
    name: Site Pages
    icon: wysiwyg
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  page_content:
    path: content/pages
    name: Page Content
    icon: dataset
    format: json
    output: false
    label_field: title
  rentals:
    path: content/rentals
    name: Rentals
    icon: holiday_village
    format: json
    output: false
    label_field: title
    schema:
      name: Rental
      fields:
        - type: text
          name: title
          label: Title
          required: true
        - type: text
          name: price
          label: Price
        - type: text
          name: address
          label: Address
        - type: textarea
          name: description
          label: Description
          rows: 4
        - type: select
          name: type
          label: Rental Type
          options:
            - label: Long-term
              value: long
            - label: Short-term
              value: short
          default: long
        - type: number
          name: bedrooms
          label: Bedrooms
          min: 0
        - type: number
          name: bathrooms
          label: Bathrooms
          min: 0
        - type: number
          name: area
          label: Area (m²)
          min: 0
        - type: number
          name: floors
          label: Floor
          min: 0
        - type: text
          name: url
          label: Detail URL
        - type: image
          name: image_1
          label: Primary Image
          directory: image/uploads
        - type: text
          name: image_1_alt
          label: Primary Image Alt Text
        - type: image
          name: image_2
          label: Secondary Image
          directory: image/uploads
        - type: text
          name: image_2_alt
          label: Secondary Image Alt Text
        - type: text
          name: image
          label: Legacy Image
          hidden: true
  properties:
    path: content/properties
    name: Properties
    icon: real_estate_agent
    format: json
    output: false
    label_field: title
    schema:
      name: Property
      fields:
        - type: text
          name: title
          label: Title
          required: true
        - type: text
          name: type
          label: Type
        - type: text
          name: price
          label: Price
        - type: text
          name: address
          label: Address
        - type: textarea
          name: description
          label: Description
          rows: 4
        - type: text
          name: url
          label: Detail URL
        - type: number
          name: bedrooms
          label: Bedrooms
          min: 0
        - type: number
          name: bathrooms
          label: Bathrooms
          min: 0
        - type: number
          name: area
          label: Area (m²)
          min: 0
        - type: number
          name: floors
          label: Floor
          min: 0
        - type: image
          name: image
          label: Featured Image
          directory: image/uploads
        - type: array
          name: gallery
          label: Gallery
          schema:
            name: Gallery Image
            fields:
              - type: image
                name: src
                label: Image
                directory: image/uploads
              - type: text
                name: alt
                label: Alt Text
              - type: text
                name: caption
                label: Caption

forms:
  rental_publish:
    name: Publish Rental
    collection: rentals
    icon: add_home_work
    description: Fill in rental details and upload both marketing images.
    fields:
      - name: title
        label: Title
        type: text
      - name: type
        label: Rental Type
        type: select
        options:
          - label: Long-term
            value: long
          - label: Short-term
            value: short
      - name: price
        label: Price
        type: text
      - name: address
        label: Address
        type: text
      - name: bedrooms
        label: Bedrooms
        type: number
      - name: bathrooms
        label: Bathrooms
        type: number
      - name: area
        label: Area (m²)
        type: number
      - name: description
        label: Description
        type: textarea
      - name: image_1
        label: Primary Image
        type: image
        directory: image/uploads
      - name: image_1_alt
        label: Primary Image Alt Text
        type: text
      - name: image_2
        label: Secondary Image
        type: image
        directory: image/uploads
      - name: image_2_alt
        label: Secondary Image Alt Text
        type: text
      - name: url
        label: Detail URL
        type: text
  property_publish:
    name: Publish Property
    collection: properties
    icon: add_business
    description: Create or update property listings, including gallery images.
    fields:
      - name: title
        label: Title
        type: text
      - name: type
        label: Property Type
        type: text
      - name: price
        label: Price
        type: text
      - name: address
        label: Address
        type: text
      - name: bedrooms
        label: Bedrooms
        type: number
      - name: bathrooms
        label: Bathrooms
        type: number
      - name: area
        label: Area (m²)
        type: number
      - name: description
        label: Description
        type: textarea
      - name: image
        label: Featured Image
        type: image
        directory: image/uploads
      - name: gallery
        label: Gallery
        type: array
        schema:
          name: Gallery Image
          fields:
            - name: src
              label: Image
              type: image
              directory: image/uploads
            - name: alt
              label: Alt Text
              type: text
            - name: caption
              label: Caption
              type: text
      - name: url
        label: Detail URL
        type: text

build:
  install: npm ci
  command: npm run build
  output_path: _site
  environment: {}
  options: {}