site:
  ssg: eleventy

build:
  base: /
  command: npm ci && npm run build
  output: _site

paths:
  uploads: image/uploads

collections_config:
  pages:
    name: Pages
    path: content/pages
    _inputs:
      slug:
        type: text
      title:
        type: text
      heroHeading:
        type: text
      heroSubheading:
        type: text

  properties:
    name: Properties
    path: content/properties
    create: true
    add_options:
      - label: New Property
        icon: home
        data:
          slug: ""
          title: ""
          price: ""
          address: ""
          description: ""
          bedrooms: 0
          bathrooms: 0
          area: 0
          floors: 0
          image: "image/dummy-img-900x700.jpg"
          imageAlt: ""
          gallery: []
    _inputs:
      slug:
        type: text
      title:
        type: text
      price:
        type: text
      address:
        type: text
      description:
        type: html
      bedrooms:
        type: number
      bathrooms:
        type: number
      area:
        type: number
      floors:
        type: number
      image:
        type: file
      imageAlt:
        type: text
      gallery:
        type: array
        schema:
          fields:
            - name: src
              label: Image
              type: file
            - name: alt
              label: Alt Text
              type: text
            - name: caption
              label: Caption
              type: text

  blog:
    name: Blog
    path: content/blog
    create: true
    _inputs:
      slug:
        type: text
      title:
        type: text
      date:
        type: datetime
      readingTime:
        type: text
      author:
        type: text
      summary:
        type: html
      image:
        type: file
      image_alt:
        type: text
      content:
        type: markdown

  rentals:
    name: Short-term Rentals
    path: content/rentals
    create: true
    _inputs:
      slug:
        type: text
      title:
        type: text
      price:
        type: text
      address:
        type: text
      description:
        type: html
      type:
        type: select
        options:
          values:
            - label: Ilgtermina
              value: long
            - label: Istermina
              value: short
      bedrooms:
        type: number
      bathrooms:
        type: number
      area:
        type: number
      floors:
        type: number
      image_1:
        type: file
      image_1_alt:
        type: text
      image_2:
        type: file
      image_2_alt:
        type: text

collection_groups:
  - heading: Content
    collections:
      - pages
      - properties
      - blog
      - rentals