_schema: _schema
paths:
  uploads: image/uploads
  static: pages
preserve_files:
  - image/uploads
collections_config:
  pages:
    path: pages
    name: Pages
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content
  content_pages:
    path: content/pages
    name: Page Content
    icon: description
    format: json
    output: false
    _enabled_editors:
      - data
  content_properties:
    path: content/properties
    name: Property Content
    icon: real_estate_agent
    format: json
    output: false
    _enabled_editors:
      - data
timezone: Europe/Riga
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
