version: 1

ssg: none
source: .

site:
  base_url: /
  timezone: Europe/Riga

paths:
  static: .
  uploads: image/uploads

routing:
  routes:
    - path: /
      file: index.html
    - path: /404.html
      file: 404.html
    - path: /{page}.html
      file: {page}.html
    - path: /properties/{slug}/
      file: properties/{slug}/index.html
    - path: /rentals/{slug}/
      file: rentals/{slug}/index.html
    - path: /blog/{slug}/
      file: blog/{slug}/index.html

collection_groups:
  - heading: Pages & Settings
    collections:
      - pages
  - heading: Listings
    collections:
      - properties
      - rentals
  - heading: Editorial
    collections:
      - blog

collections_config:
  pages:
    name: Pages
    icon: wysiwyg
    path: .
    glob:
      - index.html
      - about.html
      - blog.html
      - contact.html
      - faq.html
      - price_plan.html
      - properties.html
      - rentals.html
      - service.html
      - team.html
      - 404.html
    output: true
    editor:
      default: visual
      preview: true
    _enabled_editors:
      - visual
      - source

  properties:
    name: Properties
    icon: holiday_village
    path: properties
    glob:
      - '*/index.html'
    output: true
    create: true
    new_item_extension: html
    editor:
      default: visual
      preview: true
    _enabled_editors:
      - visual
      - source

  rentals:
    name: Rentals
    icon: home
    path: rentals
    glob:
      - '*/index.html'
    output: true
    create: true
    new_item_extension: html
    editor:
      default: visual
      preview: true
    _enabled_editors:
      - visual
      - source

  blog:
    name: Blog
    icon: article
    path: blog
    glob:
      - '*/index.html'
    output: true
    create: true
    new_item_extension: html
    editor:
      default: visual
      preview: true
    _enabled_editors:
      - visual
      - source

file_config:
  - glob: '**/*.html'
    _enabled_editors:
      - visual
      - source

build:
  install: ''
  command: ''
  output_path: .
