version: 1

ssg: none
source: .

site:
  base_url: /
  timezone: Europe/Riga

paths:
  static: .
  uploads: image/uploads
  data: data
  content: content

routing:
  routes:
    - path: /
      file: pages/index.html
    - path: /about.html
      file: pages/about.html
    - path: /blog.html
      file: pages/blog.html
    - path: /contact.html
      file: pages/contact.html
    - path: /faq.html
      file: pages/faq.html
    - path: /price_plan.html
      file: pages/price_plan.html
    - path: /properties.html
      file: pages/properties.html
    - path: /property.html
      file: pages/property.html
    - path: /property_details.html
      file: pages/property_details.html
    - path: /property-detail-template.html
      file: pages/property-detail-template.html
    - path: /rental.html
      file: pages/rental.html
    - path: /rentals.html
      file: pages/rentals.html
    - path: /service.html
      file: pages/service.html
    - path: /single_blog.html
      file: pages/single_blog.html
    - path: /team.html
      file: pages/team.html
    - path: /404.html
      file: pages/404.html

preserve_files:
  - image/uploads/**

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Listings
    collections:
      - properties
      - rentals
  - heading: Blog
    collections:
      - blog

inputs:
  short_text:
    type: text
  long_text:
    type: textarea
    options:
      rows: 4
  rich_text:
    type: markdown
    options:
      toolbar:
        - bold
        - italic
        - underline
        - link
        - bulleted_list
        - numbered_list
        - quote
  image:
    type: image
    options:
      paths:
        uploads: image/uploads
      select_existing: true
      auto_rename: true
      show_alt: true
  number:
    type: number
    options:
      min: 0
  rental_type:
    type: select
    options:
      values:
        - label: Ilgtermiņa
          value: long
        - label: Īstermiņa
          value: short

collections_config:
  pages:
    name: Pages
    path: pages
    icon: wysiwyg
    glob:
      - '**/*.html'
    base_url: /
    new_item_extension: html
    editor:
      default: visual
      preview: true
    _enabled_editors:
      - visual
      - source
  properties:
    name: Properties
    path: data/properties.json
    icon: home
    format: json
    output: false
    value_key: properties
    url: /property.html?slug={slug}
    new_item_extension: json
    _enabled_editors:
      - data
    schema:
      name: Property
      fields:
        - name: slug
          label: Slug
          type: text
        - name: title
          label: Title
          type: text
        - name: price
          label: Price
          type: text
        - name: address
          label: Address
          type: text
        - name: description
          label: Description
          type: textarea
        - name: bedrooms
          label: Bedrooms
          type: number
        - name: bathrooms
          label: Bathrooms
          type: number
        - name: area
          label: Area (m²)
          type: number
        - name: floors
          label: Floors
          type: number
        - name: image
          label: Primary Image
          type: image
        - name: gallery
          label: Gallery
          type: array
          schema:
            name: Gallery Image
            fields:
              - name: src
                label: Image
                type: image
              - name: alt
                label: Alt
                type: text
              - name: caption
                label: Caption
                type: text
  rentals:
    name: Rentals
    path: data/rentals.json
    icon: holiday_village
    format: json
    output: false
    value_key: rentals
    url: /rental.html?slug={slug}
    new_item_extension: json
    _enabled_editors:
      - data
    schema:
      name: Rental
      fields:
        - name: slug
          label: Slug
          type: text
          input: short_text
          required: true
        - name: title
          label: Title
          type: text
          input: short_text
          required: true
        - name: price
          label: Price
          type: text
          input: short_text
        - name: address
          label: Address
          type: text
          input: short_text
        - name: description
          label: Description
          type: textarea
          input: long_text
        - name: type
          label: Rental Type
          type: select
          input: rental_type
        - name: bedrooms
          label: Bedrooms
          type: number
          input: number
        - name: bathrooms
          label: Bathrooms
          type: number
          input: number
        - name: area
          label: Area (m2)
          type: number
          input: number
        - name: floors
          label: Floor
          type: number
          input: number
        - name: image_1
          label: Primary Image
          type: image
          input: image
        - name: image_1_alt
          label: Primary Image Alt Text
          type: text
          input: short_text
        - name: image_2
          label: Secondary Image
          type: image
          input: image
        - name: image_2_alt
          label: Secondary Image Alt Text
          type: text
          input: short_text
  blog:
    name: Blog
    path: data/blogs.json
    icon: article
    format: json
    output: false
    value_key: blogs
    url: /single_blog.html?slug={slug}
    new_item_extension: json
    _enabled_editors:
      - data
    schema:
      name: Blog Post
      fields:
        - name: slug
          label: Slug
          type: text
          input: short_text
          required: true
        - name: title
          label: Title
          type: text
          input: short_text
          required: true
        - name: date
          label: Published Date
          type: date
        - name: readingTime
          label: Reading Time
          type: text
          input: short_text
        - name: author
          label: Author
          type: text
          input: short_text
        - name: summary
          label: Summary
          type: textarea
          input: long_text
        - name: image
          label: Featured Image
          type: image
          input: image
        - name: image_alt
          label: Featured Image Alt Text
          type: text
          input: short_text
        - name: content
          label: Post Body
          type: array
          schema:
            name: Section
            type: markdown
            input: rich_text

file_config:
  - glob: pages/**/*.html
    _enabled_editors:
      - visual
      - source
  - glob: data/**/*.json
    _enabled_editors:
      - data

source_editor:
  enabled: true
  commit_templates:
    - label: Content update
      template: "content: update {{ collection }}"

build:
  install: ""
  command: ""
  output_path: .
























